"""App table layout, row keys, the time shift, and ordered reads from prepared Parquet."""

from __future__ import annotations

import heapq
from collections.abc import Iterator
from datetime import UTC, date, datetime, timedelta

import duckdb

from saas_stream.settings import parquet_path

# Data columns per table, parents first. Every app table also has event_ts,
# source_event_ts, ingested_at, ingest_id, is_backfill, and is_demo.
DATA_COLUMNS: dict[str, list[str]] = {
    "accounts": [
        "account_id", "created_at", "account_type", "signup_plan", "price_version",
        "trial_started_at", "trial_ends_at", "currency", "is_nonprofit", "is_internal",
    ],
    "users": ["user_id", "account_id", "role", "invited_at"],
    "devices": [
        "device_id", "account_id", "user_id", "device_fingerprint", "os", "is_tagged",
        "registered_at",
    ],
    "usage_daily": [
        "account_id", "activity_date", "active_users", "user_devices", "tagged_resources",
        "ephemeral_minutes",
    ],
    "feature_usage_daily": ["account_id", "activity_date", "feature", "attempts", "gated_blocked"],
    "license_events": [
        "license_event_id", "account_id", "user_id", "event_type", "licenses_held_after",
        "licenses_used_after",
    ],
    "plan_changes": [
        "plan_change_id", "account_id", "from_plan", "to_plan", "from_price_version",
        "to_price_version", "change_source",
    ],
    "invoices": [
        "invoice_id", "account_id", "status", "currency", "subtotal", "subtotal_usd",
        "discount_total", "discount_total_usd", "tax", "tax_usd", "total", "total_usd",
        "invoice_date", "service_period_start", "service_period_end", "due_date", "paid_at",
    ],
    "payments": [
        "payment_id", "account_id", "invoice_id", "status", "currency", "amount", "amount_usd",
        "amount_refunded", "amount_refunded_usd", "is_test", "paid", "captured", "refunded",
    ],
}  # fmt: skip

# Live-only tables: generated by `make demo` from the daily rows of DEMO_DATE.
LIVE_COLUMNS: dict[str, list[str]] = {
    "sessions": ["session_id", "account_id", "user_id", "device_id", "started_at", "duration_s"],
    "feature_events": [
        "event_id", "account_id", "user_id", "feature", "gated_blocked", "occurred_at",
    ],
}  # fmt: skip

# Display timestamp columns. On live rows they are written as now() plus their
# offset from the event time, so they line up with event_ts.
DISPLAY_TIMES = {
    "accounts": ["created_at", "trial_started_at", "trial_ends_at"],
    "users": ["invited_at"],
    "devices": ["registered_at"],
    "sessions": ["started_at"],
    "feature_events": ["occurred_at"],
    "invoices": ["paid_at"],
}

TABLE_NAMES = list(DATA_COLUMNS)  # tables with prepared Parquet history
COLUMNS = DATA_COLUMNS | LIVE_COLUMNS
# Every app table, parents before children.
APP_TABLES = [
    "accounts", "users", "devices", "sessions", "usage_daily", "feature_usage_daily",
    "feature_events", "license_events", "plan_changes", "invoices", "payments",
]  # fmt: skip
RANK = {table: rank for rank, table in enumerate(APP_TABLES)}
KEYS = {
    "accounts": ["account_id"],
    "users": ["user_id"],
    "devices": ["device_id"],
    "usage_daily": ["account_id", "activity_date"],
    "feature_usage_daily": ["account_id", "activity_date", "feature"],
    "license_events": ["license_event_id"],
    "plan_changes": ["plan_change_id"],
    "invoices": ["invoice_id"],
    "payments": ["payment_id"],
    "sessions": ["session_id"],
    "feature_events": ["event_id"],
}
LOAD_COLUMNS = {
    table: columns + ["event_ts", "source_event_ts", "is_backfill", "is_demo", "is_injected"]
    for table, columns in DATA_COLUMNS.items()
}


def row_key(table: str, row: dict) -> str:
    return "|".join(str(row[key]) for key in KEYS[table])


def shift_row(row: dict, days: int) -> dict:
    """Shift every date and timestamp by `days`; keep the original event_ts as source_event_ts.

    Parquet timestamps are naive UTC; the result is timezone-aware, like rows read back
    from Postgres, so both compare cleanly.
    """
    delta = timedelta(days=days)
    shifted = {}
    for column, value in row.items():
        if isinstance(value, datetime):
            value = utc(value) + delta
        elif isinstance(value, date):
            value = value + delta
        shifted[column] = value
    shifted["source_event_ts"] = utc(row["event_ts"])
    return shifted


def utc(value: datetime) -> datetime:
    return value if value.tzinfo else value.replace(tzinfo=UTC)


def source_rows(
    table: str,
    *,
    start: datetime | None = None,
    end: datetime | None = None,
    after: tuple[datetime, int, str] | None = None,
) -> Iterator[tuple[tuple[datetime, int, str], dict]]:
    """Yield ((event_ts, rank, source_key), row) from Parquet in event order.

    `after` is a resume cursor over the merged stream of all tables.
    """
    rank = RANK[table]
    columns = DATA_COLUMNS[table] + ["event_ts"]
    keys = ", ".join(f"CAST({key} AS VARCHAR)" for key in KEYS[table])
    where, params = ["true"], [str(parquet_path(table))]
    if start is not None:
        where.append("event_ts >= ?")
        params.append(start)
    if end is not None:
        where.append("event_ts < ?")
        params.append(end)
    if after is not None:
        ts, after_rank, after_key = after
        if rank < after_rank:
            where.append("event_ts > ?")
            params.append(ts)
        elif rank > after_rank:
            where.append("event_ts >= ?")
            params.append(ts)
        else:
            where.append("(event_ts > ? OR (event_ts = ? AND source_key > ?))")
            params += [ts, ts, after_key]
    query = f"""
        SELECT * FROM (
            SELECT {", ".join(columns)}, concat_ws('|', {keys}) AS source_key
            FROM read_parquet(?)
        )
        WHERE {" AND ".join(where)}
        ORDER BY event_ts, source_key
    """
    reader = duckdb.connect().execute(query, params)
    while chunk := reader.fetchmany(5_000):
        for values in chunk:
            row = dict(zip(columns, values[:-1], strict=True))
            yield (row["event_ts"], rank, values[-1]), row


def merged_source_rows(
    *, start: datetime | None = None, after: tuple[datetime, int, str] | None = None
) -> Iterator[tuple[tuple[datetime, int, str], str, dict]]:
    """All tables merged in (event_ts, rank, key) order: parents before children."""
    def tagged(table: str):
        for position, row in source_rows(table, start=start, after=after):
            yield position, table, row

    streams = [tagged(table) for table in TABLE_NAMES]
    return heapq.merge(*streams, key=lambda item: item[0])
